from app import db
from models import Subreddit, Symbol, RedditHeat, Index, User, UserSymbol
from random import randint

db.drop_all()
db.create_all()
# Create seed subs
sub_names = [
    "investing",
    "wallstreetbets",
    "robinhood",
    "stocks",
]

for sub in sub_names:
    new_sub = Subreddit(name = sub)
    db.session.add(new_sub)
    db.session.commit()

# Create seed Indexes
nyse = Index(name = "New York Stock Exchange", symbol = "NYSE")
nasdaq = Index(name = "Nasdaq", symbol = "NASDAQ")
db.session.add_all([nyse, nasdaq])
db.session.commit()

# Create some seed Stock Symbols
s_and_p_500 = [ # List end line 281'ish
    ("MMM", "3M Company", nyse.id), ("A", "Agilent Technologies Inc", nyse.id),
    ("AAL", "American Airlines Group", nasdaq.id), ("AAP", "Advance Auto Parts", nyse.id),
    ("AAPL", "Apple Inc.", nasdaq.id), ("ABBV", "AbbVie Inc.", nyse.id),
    ("ABC", "AmerisourceBergen Corp", nyse.id), ("ABMD", "ABIOMED Inc", nasdaq.id),
    ("ABT", "Abbott Laboratories", nyse.id), ("ACN", "Accenture plc", nyse.id),
    ("ADBE", "Adobe Inc.", nasdaq.id), ("ADI", "Analog Devices Inc.", nasdaq.id),
    ("ADM", "Archer-Daniels-Midland Co", nyse.id), ("ADP", "Automatic Data Processing", nasdaq.id),
    ("ADSK", "Autodesk Inc.", nasdaq.id), ("AEE", "Ameren Corp", nyse.id),
    ("AEP", "American Electric Power", nyse.id), ("AES", "AES Corp", nyse.id),
    ("AFL", "AFLAC Inc", nyse.id), ("AIG", "American International Group", nyse.id),
    ("AIV", "Apartment Investment & Management", nyse.id), ("AIZ", "Assurant", nyse.id),
    ("AJG", "Arthur J. Gallagher & Co.", nyse.id), ("AKAM", "Akamai Technologies Inc", nasdaq.id),
    ("ALB", "Albemarle Corp", nyse.id), ("ALGN", "Align Technology", nasdaq.id),
    ("ALK", "Alaska Air Group Inc", nyse.id), ("ALL", "Allstate Corp", nyse.id),
    ("ALLE", "Allegion", nyse.id), ("ALXN", "Alexion Pharmaceuticals", nasdaq.id),
    ("AMAT", "Applied Materials Inc.", nasdaq.id), ("AMCR", "Amcor plc", nyse.id),
    ("AMD", "Advanced Micro Devices Inc", nasdaq.id), ("AME", "AMETEK Inc.", nyse.id),
    ("AMGN", "Amgen Inc.", nasdaq.id), ("AMP", "Ameriprise Financial", nyse.id),
    ("AMT", "American Tower Corp.", nyse.id), ("AMZN", "Amazon.com Inc.", nasdaq.id),
    ("ANET", "Arista Networks", nyse.id), ("ANSS", "ANSYS", nasdaq.id),
    ("ANTM", "Anthem", nyse.id), ("AON", "Aon plc", nyse.id),
    ("AOS", "A.O. Smith Corp", nyse.id), ("APA", "Apache Corporation", nasdaq.id),
    ("APD", "Air Products & Chemicals Inc", nyse.id), ("APH", "Amphenol Corp", nyse.id),
    ("APTV", "Aptiv PLC", nyse.id), ("ARE", "Alexandria Real Estate Equities", nyse.id),
    ("ATO", "Atmos Energy", nyse.id), ("ATVI", "Activision Blizzard", nasdaq.id),
    ("AVB", "AvalonBay Communities", nyse.id), ("AVGO", "Broadcom Inc.", nasdaq.id),
    ("AVY", "Avery Dennison Corp", nyse.id), ("AWK", "American Water Works Company Inc", nyse.id),
    ("AXP", "American Express Co", nyse.id), ("AZO", "AutoZone Inc", nyse.id),
    ("BA", "Boeing Company", nyse.id), ("BAC", "Bank of America Corp", nyse.id),
    ("BAX", "Baxter International Inc.", nyse.id), ("BBY", "Best Buy Co. Inc.", nyse.id),
    ("BDX", "Becton Dickinson", nyse.id), ("BEN", "Franklin Resources", nyse.id),
    ("BF.B", "Brown-Forman Corp.", nyse.id), ("BIIB", "Biogen Inc.", nasdaq.id),
    ("BIO", "Bio-Rad Laboratories", nyse.id), ("BK", "The Bank of New York Mellon", nyse.id),
    ("BKNG", "Booking Holdings Inc", nasdaq.id), ("BKR", "Baker Hughes Co", nyse.id),
    ("BLK", "BlackRock", nyse.id), ("BLL", "Ball Corp", nyse.id),
    ("BMY", "Bristol-Myers Squibb", nyse.id), ("BR", "Broadridge Financial Solutions", nyse.id),
    ("BRK.B", "Berkshire Hathaway", nyse.id), ("BSX", "Boston Scientific", nyse.id),
    ("BWA", "BorgWarner", nyse.id), ("BXP", "Boston Properties", nyse.id),
    ("C", "Citigroup Inc.", nyse.id), ("CAG", "Conagra Brands", nyse.id),
    ("CAH", "Cardinal Health Inc.", nyse.id), ("CARR", "Carrier Global", nyse.id),
    ("CAT", "Caterpillar Inc.", nyse.id), ("CB", "Chubb Limited", nyse.id),
    ("CBRE", "CBRE Group", nyse.id), ("CCI", "Crown Castle International Corp.", nyse.id),
    ("CCL", "Carnival Corp.", nyse.id), ("CDNS", "Cadence Design Systems", nasdaq.id),
    ("CDW", "CDW", nasdaq.id), ("CE", "Celanese", nyse.id),
    ("CERN", "Cerner", nasdaq.id), ("CF", "CF Industries Holdings Inc", nyse.id),
    ("CFG", "Citizens Financial Group", nyse.id), ("CHD", "Church & Dwight", nyse.id),
    ("CHRW", "C. H. Robinson Worldwide", nasdaq.id), ("CHTR", "Charter Communications", nasdaq.id),
    ("CI", "CIGNA Corp.", nyse.id), ("CINF", "Cincinnati Financial", nasdaq.id),
    ("CL", "Colgate-Palmolive", nyse.id), ("CLX", "The Clorox Company", nyse.id),
    ("CMA", "Comerica Inc.", nyse.id), ("CMCSA", "Comcast Corp.", nasdaq.id),
    ("CME", "CME Group Inc.", nasdaq.id), ("CMG", "Chipotle Mexican Grill", nyse.id),
    ("CMI", "Cummins Inc.", nyse.id), ("CMS", "CMS Energy", nyse.id),
    ("CNC", "Centene Corporation", nyse.id), ("CNP", "CenterPoint Energy", nyse.id),
    ("COF", "Capital One Financial", nyse.id), ("COG", "Cabot Oil & Gas", nyse.id),
    ("COO", "The Cooper Companies", nyse.id), ("COP", "ConocoPhillips", nyse.id),
    ("COST", "Costco Wholesale Corp.", nasdaq.id), ("CPB", "Campbell Soup", nyse.id),
    ("CPRT", "Copart Inc", nasdaq.id), ("CRM", "Salesforce.com", nyse.id),
    ("CSCO", "Cisco Systems", nasdaq.id), ("CSX", "CSX Corp.", nasdaq.id),
    ("CTAS", "Cintas Corporation", nasdaq.id), ("CTLT", "Catalent", nyse.id),
    ("CTSH", "Cognizant Technology Solutions", nasdaq.id), ("CTVA", "Corteva", nyse.id),
    ("CTXS", "Citrix Systems", nasdaq.id), ("CVS", "CVS Health", nyse.id),
    ("CVX", "Chevron Corp.", nyse.id), ("CXO", "Concho Resources", nyse.id),
    ("D", "Dominion Energy", nyse.id), ("DAL", "Delta Air Lines Inc.", nyse.id),
    ("DD", "DuPont de Nemours Inc", nyse.id), ("DE", "Deere & Co.", nyse.id),
    ("DFS", "Discover Financial Services", nyse.id), ("DG", "Dollar General", nyse.id),
    ("DGX", "Quest Diagnostics", nyse.id), ("DHI", "D. R. Horton", nyse.id),
    ("DHR", "Danaher Corp.", nyse.id), ("DIS", "The Walt Disney Company", nyse.id),
    ("DISCA", "Discovery Inc. (Class A)", nasdaq.id), ("DISCK", "Discovery Inc. (Class C)", nasdaq.id),
    ("DISH", "Dish Network", nasdaq.id), ("DLR", "Digital Realty Trust Inc", nyse.id),
    ("DLTR", "Dollar Tree", nasdaq.id), ("DOV", "Dover Corporation", nyse.id),
    ("DOW", "Dow Inc.", nyse.id), ("DPZ", "Domino's Pizza", nyse.id),
    ("DRE", "Duke Realty Corp", nyse.id), ("DRI", "Darden Restaurants", nyse.id),
    ("DTE", "DTE Energy Co.", nyse.id), ("DUK", "Duke Energy", nyse.id),
    ("DVA", "DaVita Inc.", nyse.id), ("DVN", "Devon Energy", nyse.id),
    ("DXC", "DXC Technology", nyse.id), ("DXCM", "DexCom", nasdaq.id),
    ("EA", "Electronic Arts", nasdaq.id), ("EBAY", "eBay Inc.", nasdaq.id),
    ("ECL", "Ecolab Inc.", nyse.id), ("ED", "Consolidated Edison", nyse.id),
    ("EFX", "Equifax Inc.", nyse.id), ("EIX", "Edison Int'l", nyse.id),
    ("EL", "Estée Lauder Companies", nyse.id), ("EMN", "Eastman Chemical", nyse.id),
    ("EMR", "Emerson Electric Company", nyse.id), ("ENPH", "Enphase Enery", nasdaq.id),
    ("EOG", "EOG Resources", nyse.id), ("EQIX", "Equinix", nasdaq.id),
    ("EQR", "Equity Residential", nyse.id), ("ES", "Eversource Energy", nyse.id),
    ("ESS", "Essex Property Trust Inc.", nyse.id), ("ETN", "Eaton Corporation", nyse.id),
    ("ETR", "Entergy Corp.", nyse.id), ("ETSY", "Etsy", nasdaq.id),
    ("EVRG", "Evergy", nyse.id), ("EW", "Edwards Lifesciences", nyse.id),
    ("EXC", "Exelon Corp.", nyse.id), ("EXPD", "Expeditors", nasdaq.id),
    ("EXPE", "Expedia Group", nasdaq.id), ("EXR", "Extra Space Storage", nyse.id),
    ("F", "Ford Motor Company", nyse.id), ("FANG", "Diamondback Energy", nasdaq.id),
    ("FAST", "Fastenal Co", nasdaq.id), ("FB", "Facebook Inc.", nasdaq.id),
    ("FBHS", "Fortune Brands Home & Security", nyse.id), ("FCX", "Freeport-McMoRan Inc.", nyse.id),
    ("FDX", "FedEx Corporation", nyse.id), ("FE", "FirstEnergy Corp", nyse.id),
    ("FFIV", "F5 Networks", nasdaq.id), ("FIS", "Fidelity National Information Services", nyse.id),
    ("FISV", "Fiserv Inc", nasdaq.id), ("FITB", "Fifth Third Bancorp", nasdaq.id),
    ("FLIR", "FLIR Systems", nasdaq.id), ("FLS", "Flowserve Corporation", nyse.id),
    ("FLT", "FleetCor Technologies Inc", nyse.id), ("FMC", "FMC Corporation", nyse.id),
    ("FOX", "Fox Corporation (Class B)", nasdaq.id), ("FOXA", "Fox Corporation (Class A)", nasdaq.id),
    ("FRC", "First Republic Bank", nyse.id), ("FRT", "Federal Realty Investment Trust", nyse.id),
    ("FTI", "TechnipFMC", nyse.id), ("FTNT", "Fortinet", nasdaq.id),
    ("FTV", "Fortive Corp", nyse.id), ("GD", "General Dynamics", nyse.id),
    ("GE", "General Electric", nyse.id), ("GILD", "Gilead Sciences", nasdaq.id),
    ("GIS", "General Mills", nyse.id), ("GL", "Globe Life Inc.", nyse.id),
    ("GLW", "Corning Inc.", nyse.id), ("GM", "General Motors", nyse.id),
    ("GOOG", "Alphabet Inc. (Class C)", nasdaq.id), ("GOOGL", "Alphabet Inc. (Class A)", nasdaq.id),
    ("GPC", "Genuine Parts", nyse.id), ("GPN", "Global Payments Inc.", nyse.id),
    ("GPS", "Gap Inc.", nyse.id), ("GRMN", "Garmin Ltd.", nasdaq.id),
    ("GS", "Goldman Sachs Group", nyse.id), ("GWW", "Grainger (W.W.) Inc.", nyse.id),
    ("HAL", "Halliburton Co.", nyse.id), ("HAS", "Hasbro Inc.", nasdaq.id),
    ("HBAN", "Huntington Bancshares", nasdaq.id), ("HBI", "Hanesbrands Inc", nyse.id),
    ("HCA", "HCA Healthcare", nyse.id), ("HD", "Home Depot", nyse.id),
    ("HES", "Hess Corporation", nyse.id), ("HFC", "HollyFrontier Corp", nyse.id),
    ("HIG", "Hartford Financial Svc.Gp.", nyse.id), ("HII", "Huntington Ingalls Industries", nyse.id),
    ("HLT", "Hilton Worldwide Holdings Inc", nyse.id), ("HOLX", "Hologic", nasdaq.id),
    ("HON", "Honeywell Int'l Inc.", nyse.id), ("HPE", "Hewlett Packard Enterprise", nyse.id),
    ("HPQ", "HP Inc.", nyse.id), ("HRL", "Hormel Foods Corp.", nyse.id),
    ("HSIC", "Henry Schein", nasdaq.id), ("HST", "Host Hotels & Resorts", nyse.id),
    ("HSY", "The Hershey Company", nyse.id), ("HUM", "Humana Inc.", nyse.id),
    ("HWM", "Howmet Aerospace", nyse.id), ("IBM", "International Business Machines", nyse.id),
    ("ICE", "Intercontinental Exchange", nyse.id), ("IDXX", "IDEXX Laboratories", nasdaq.id),
    ("IEX", "IDEX Corporation", nyse.id), ("IFF", "International Flavors & Fragrances", nyse.id),
    ("ILMN", "Illumina Inc", nasdaq.id), ("INCY", "Incyte", nasdaq.id),
    ("INFO", "IHS Markit Ltd.", nasdaq.id), ("INTC", "Intel Corp.", nasdaq.id),
    ("INTU", "Intuit Inc.", nasdaq.id), ("IP", "International Paper", nyse.id),
    ("IPG", "Interpublic Group", nyse.id), ("IPGP", "IPG Photonics Corp.", nasdaq.id),
    ("IQV", "IQVIA Holdings Inc.", nyse.id), ("IR", "Ingersoll Rand", nyse.id),
    ("IRM", "Iron Mountain Incorporated", nyse.id), ("ISRG", "Intuitive Surgical Inc.", nasdaq.id),
    ("IT", "Gartner Inc", nyse.id), ("ITW", "Illinois Tool Works", nyse.id),
    ("IVZ", "Invesco Ltd.", nyse.id), ("J", "Jacobs Engineering Group", nyse.id),
    ("JBHT", "J. B. Hunt Transport Services", nasdaq.id), ("JCI", "Johnson Controls International", nyse.id),
    ("JKHY", "Jack Henry & Associates", nasdaq.id), ("JNJ", "Johnson & Johnson", nyse.id),
    ("JNPR", "Juniper Networks", nyse.id), ("JPM", "JPMorgan Chase & Co.", nyse.id),
    ("K", "Kellogg Co.", nyse.id), ("KEY", "KeyCorp", nyse.id),
    ("KEYS", "Keysight Technologies", nyse.id), ("KHC", "Kraft Heinz Co", nasdaq.id),
    ("KIM", "Kimco Realty", nyse.id), ("KLAC", "KLA Corporation", nasdaq.id),
    ("KMB", "Kimberly-Clark", nyse.id), ("KMI", "Kinder Morgan", nyse.id),
    ("KMX", "Carmax Inc", nyse.id), ("KO", "Coca-Cola Company", nyse.id),
    ("KR", "Kroger Co.", nyse.id), ("KSU", "Kansas City Southern", nyse.id),
    ("L", "Loews Corp.", nyse.id), ("LB", "L Brands Inc.", nyse.id),
    ("LDOS", "Leidos Holdings", nyse.id), ("LEG", "Leggett & Platt", nyse.id),
    ("LEN", "Lennar Corp.", nyse.id), ("LH", "Laboratory Corp. of America Holding", nyse.id),
    ("LHX", "L3Harris Technologies", nyse.id), ("LIN", "Linde plc", nyse.id),
    ("LKQ", "LKQ Corporation", nasdaq.id), ("LLY", "Lilly (Eli) & Co.", nyse.id),
    ("LMT", "Lockheed Martin Corp.", nyse.id), ("LNC", "Lincoln National", nyse.id),
    ("LNT", "Alliant Energy Corp", nyse.id), ("LOW", "Lowe's Cos.", nyse.id),
    ("LRCX", "Lam Research", nasdaq.id), ("LUMN", "Lumen Technolgies", nyse.id),
    ("LUV", "Southwest Airlines", nyse.id), ("LVS", "Las Vegas Sands", nyse.id),
    ("LW", "Lamb Weston Holdings Inc", nyse.id), ("LYB", "LyondellBasell", nyse.id),
    ("LYV", "Live Nation Entertainment", nyse.id), ("MA", "Mastercard Inc.", nyse.id),
    ("MAA", "Mid-America Apartments", nyse.id), ("MAR", "Marriott Int'l.", nasdaq.id),
    ("MAS", "Masco Corp.", nyse.id), ("MCD", "McDonald's Corp.", nyse.id),
    ("MCHP", "Microchip Technology", nasdaq.id), ("MCK", "McKesson Corp.", nyse.id),
    ("MCO", "Moody's Corp", nyse.id), ("MDLZ", "Mondelez International", nasdaq.id),
    ("MDT", "Medtronic plc", nyse.id), ("MET", "MetLife Inc.", nyse.id),
    ("MGM", "MGM Resorts International", nyse.id), ("MHK", "Mohawk Industries", nyse.id),
    ("MKC", "McCormick & Co.", nyse.id), ("MKTX", "MarketAxess", nasdaq.id),
    ("MLM", "Martin Marietta Materials", nyse.id), ("MMC", "Marsh & McLennan", nyse.id),
    ("MNST", "Monster Beverage", nasdaq.id), ("MO", "Altria Group Inc", nyse.id),
    ("MOS", "The Mosaic Company", nyse.id), ("MPC", "Marathon Petroleum", nyse.id),
    ("MRK", "Merck & Co.", nyse.id), ("MRO", "Marathon Oil Corp.", nyse.id),
    ("MS", "Morgan Stanley", nyse.id), ("MSCI", "MSCI Inc", nyse.id),
    ("MSFT", "Microsoft Corp.", nasdaq.id), ("MSI", "Motorola Solutions Inc.", nyse.id),
    ("MTB", "M&T Bank Corp.", nyse.id), ("MTD", "Mettler Toledo", nyse.id),
    ("MU", "Micron Technology", nasdaq.id), ("MXIM", "Maxim Integrated Products Inc", nasdaq.id),
    ("NCLH", "Norwegian Cruise Line Holdings", nyse.id), ("NDAQ", "Nasdaq Inc.", nasdaq.id),
    ("NEE", "NextEra Energy", nyse.id), ("NEM", "Newmont Corporation", nyse.id),
    ("NFLX", "Netflix Inc.", nasdaq.id), ("NI", "NiSource Inc.", nyse.id),
    ("NKE", "Nike Inc.", nyse.id), ("NLOK", "NortonLifeLock", nasdaq.id),
    ("NLSN", "Nielsen Holdings", nyse.id), ("NOC", "Northrop Grumman", nyse.id),
    ("NOV", "NOV Inc.", nyse.id), ("NOW", "ServiceNow", nyse.id),
    ("NRG", "NRG Energy", nyse.id), ("NSC", "Norfolk Southern Corp.", nyse.id),
    ("NTAP", "NetApp", nasdaq.id), ("NTRS", "Northern Trust Corp.", nasdaq.id),
    ("NUE", "Nucor Corp.", nyse.id), ("NVDA", "Nvidia Corporation", nasdaq.id),
    ("NVR", "NVR Inc.", nyse.id), ("NWL", "Newell Brands", nasdaq.id),
    ("NWS", "News Corp. Class B", nasdaq.id), ("NWSA", "News Corp. Class A", nasdaq.id),
    ("O", "Realty Income Corporation", nyse.id), ("ODFL", "Old Dominion Freight Line", nasdaq.id),
    ("OKE", "ONEOK", nyse.id), ("OMC", "Omnicom Group", nyse.id),
    ("ORCL", "Oracle Corp.", nyse.id), ("ORLY", "O'Reilly Automotive", nasdaq.id),
    ("OTIS", "Otis Worldwide", nyse.id), ("OXY", "Occidental Petroleum", nyse.id),
    ("PAYC", "Paycom", nyse.id), ("PAYX", "Paychex Inc.", nasdaq.id),
    ("PBCT", "People's United Financial", nasdaq.id), ("PCAR", "PACCAR Inc.", nasdaq.id),
    ("PEAK", "Healthpeak Properties", nyse.id), ("PEG", "Public Service Enterprise Group (PSEG)", nyse.id),
    ("PEP", "PepsiCo Inc.", nasdaq.id), ("PFE", "Pfizer Inc.", nyse.id),
    ("PFG", "Principal Financial Group", nyse.id), ("PG", "Procter & Gamble", nyse.id),
    ("PGR", "Progressive Corp.", nyse.id), ("PH", "Parker-Hannifin", nyse.id),
    ("PHM", "PulteGroup", nyse.id), ("PKG", "Packaging Corporation of America", nyse.id),
    ("PKI", "PerkinElmer", nyse.id), ("PLD", "Prologis", nyse.id),
    ("PM", "Philip Morris International", nyse.id), ("PNC", "PNC Financial Services", nyse.id),
    ("PNR", "Pentair plc", nyse.id), ("PNW", "Pinnacle West Capital", nyse.id),
    ("POOL", "Pool Corporation", nasdaq.id), ("PPG", "PPG Industries", nyse.id),
    ("PPL", "PPL Corp.", nyse.id), ("PRGO", "Perrigo", nyse.id),
    ("PRU", "Prudential Financial", nyse.id), ("PSA", "Public Storage", nyse.id),
    ("PSX", "Phillips 66", nyse.id), ("PVH", "PVH Corp.", nyse.id),
    ("PWR", "Quanta Services Inc.", nyse.id), ("PXD", "Pioneer Natural Resources", nyse.id),
    ("PYPL", "PayPal", nasdaq.id), ("QCOM", "QUALCOMM Inc.", nasdaq.id),
    ("QRVO", "Qorvo", nasdaq.id), ("RCL", "Royal Caribbean Group", nyse.id),
    ("RE", "Everest Re Group Ltd.", nyse.id), ("REG", "Regency Centers Corporation", nyse.id),
    ("REGN", "Regeneron Pharmaceuticals", nasdaq.id), ("RF", "Regions Financial Corp.", nyse.id),
    ("RHI", "Robert Half International", nyse.id), ("RJF", "Raymond James Financial Inc.", nyse.id),
    ("RL", "Ralph Lauren Corporation", nyse.id), ("RMD", "ResMed", nyse.id),
    ("ROK", "Rockwell Automation Inc.", nyse.id), ("ROL", "Rollins Inc.", nyse.id),
    ("ROP", "Roper Technologies", nyse.id), ("ROST", "Ross Stores", nasdaq.id),
    ("RSG", "Republic Services Inc", nyse.id), ("RTX", "Raytheon Technologies", nyse.id),
    ("SBAC", "SBA Communications", nasdaq.id), ("SBUX", "Starbucks Corp.", nasdaq.id),
    ("SCHW", "Charles Schwab Corporation", nyse.id), ("SEE", "Sealed Air", nyse.id),
    ("SHW", "Sherwin-Williams", nyse.id), ("SIVB", "SVB Financial", nasdaq.id),
    ("SJM", "JM Smucker", nyse.id), ("SLB", "Schlumberger Ltd.", nyse.id),
    ("SLG", "SL Green Realty", nyse.id), ("SNA", "Snap-on", nyse.id),
    ("SNPS", "Synopsys Inc.", nasdaq.id), ("SO", "Southern Company", nyse.id),
    ("SPG", "Simon Property Group Inc", nyse.id), ("SPGI", "S&P Global Inc.", nyse.id),
    ("SRE", "Sempra Energy", nyse.id), ("STE", "STERIS plc", nyse.id),
    ("STT", "State Street Corp.", nyse.id), ("STX", "Seagate Technology", nasdaq.id),
    ("STZ", "Constellation Brands", nyse.id), ("SWK", "Stanley Black & Decker", nyse.id),
    ("SWKS", "Skyworks Solutions", nasdaq.id), ("SYF", "Synchrony Financial", nyse.id),
    ("SYK", "Stryker Corp.", nyse.id), ("SYY", "Sysco Corp.", nyse.id),
    ("T", "AT&T Inc.", nyse.id), ("TAP", "Molson Coors Beverage Company", nyse.id),
    ("TDG", "TransDigm Group", nyse.id), ("TDY", "Teledyne Technologies", nyse.id),
    ("TEL", "TE Connectivity Ltd.", nyse.id), ("TER", "Teradyne", nasdaq.id),
    ("TFC", "Truist Financial", nyse.id), ("TFX", "Teleflex", nyse.id),
    ("TGT", "Target Corp.", nyse.id), ("TJX", "TJX Companies Inc.", nyse.id),
    ("TMO", "Thermo Fisher Scientific", nyse.id), ("TMUS", "T-Mobile US", nasdaq.id),
    ("TPR", "Tapestry Inc.", nyse.id), ("TROW", "T. Rowe Price Group", nasdaq.id),
    ("TRV", "The Travelers Companies Inc.", nyse.id), ("TSCO", "Tractor Supply Company", nasdaq.id),
    ("TSLA", "Tesla, Inc.", nasdaq.id), ("TSN", "Tyson Foods", nyse.id),
    ("TT", "Trane Technologies plc", nyse.id), ("TTWO", "Take-Two Interactive", nasdaq.id),
    ("TWTR", "Twitter Inc.", nyse.id), ("TXN", "Texas Instruments", nasdaq.id),
    ("TXT", "Textron Inc.", nyse.id), ("TYL", "Tyler Technologies", nyse.id),
    ("UA", "Under Armour (Class C)", nyse.id), ("UAA", "Under Armour (Class A)", nyse.id),
    ("UAL", "United Airlines Holdings", nasdaq.id), ("UDR", "UDR Inc.", nyse.id),
    ("UHS", "Universal Health Services", nyse.id), ("ULTA", "Ulta Beauty", nasdaq.id),
    ("UNH", "United Health Group Inc.", nyse.id), ("UNM", "Unum Group", nyse.id),
    ("UNP", "Union Pacific Corp", nyse.id), ("UPS", "United Parcel Service", nyse.id),
    ("URI", "United Rentals Inc.", nyse.id), ("USB", "U.S. Bancorp", nyse.id),
    ("V", "Visa Inc.", nyse.id), ("VAR", "Varian Medical Systems", nyse.id),
    ("VFC", "VF Corporation", nyse.id), ("VIAC", "ViacomCBS", nasdaq.id),
    ("VLO", "Valero Energy", nyse.id), ("VMC", "Vulcan Materials", nyse.id),
    ("VNO", "Vornado Realty Trust", nyse.id), ("VNT", "Vontier", nyse.id),
    ("VRSK", "Verisk Analytics", nasdaq.id), ("VRSN", "Verisign Inc.", nasdaq.id),
    ("VRTX", "Vertex Pharmaceuticals Inc", nasdaq.id), ("VTR", "Ventas Inc", nyse.id),
    ("VTRS", "Viatris", nasdaq.id), ("VZ", "Verizon Communications", nyse.id),
    ("WAB", "Westinghouse Air Brake Technologies Corp", nyse.id), ("WAT", "Waters Corporation", nyse.id),
    ("WBA", "Walgreens Boots Alliance", nasdaq.id), ("WDC", "Western Digital", nasdaq.id),
    ("WEC", "WEC Energy Group", nyse.id), ("WELL", "Welltower Inc.", nyse.id),
    ("WFC", "Wells Fargo", nyse.id), ("WHR", "Whirlpool Corp.", nyse.id),
    ("WLTW", "Willis Towers Watson", nasdaq.id), ("WM", "Waste Management Inc.", nyse.id),
    ("WMB", "Williams Companies", nyse.id), ("WMT", "Walmart", nyse.id),
    ("WRB", "W. R. Berkley Corporation", nyse.id), ("WRK", "WestRock", nyse.id),
    ("WST", "West Pharmaceutical Services", nyse.id), ("WU", "Western Union Co", nyse.id),
    ("WY", "Weyerhaeuser", nyse.id), ("WYNN", "Wynn Resorts Ltd", nasdaq.id),
    ("XEL", "Xcel Energy Inc", nasdaq.id), ("XLNX", "Xilinx", nasdaq.id),
    ("XOM", "Exxon Mobil Corp.", nyse.id), ("XRAY", "Dentsply Sirona", nasdaq.id),
    ("XRX", "Xerox", nyse.id), ("XYL", "Xylem Inc.", nyse.id),
    ("YUM", "Yum! Brands Inc", nyse.id), ("ZBH", "Zimmer Biomet Holdings", nyse.id),
    ("ZBRA", "Zebra Technologies", nasdaq.id), ("ZION", "Zions Bancorp", nasdaq.id),
    ("ZTS", "Zoetis", nyse.id)
]

seed_dates = [
    "2021-01-01", "2021-01-02", "2021-01-03", "2021-01-04", "2021-01-05",
    "2021-01-06", "2021-01-07", "2021-01-08", "2021-01-09", "2021-01-10",
    "2021-01-11", "2021-01-12", "2021-01-13", "2021-01-14", "2021-01-15",
    "2021-01-16", "2021-01-17", "2021-01-18", "2021-01-19", "2021-01-20"
]
# Add the symbols to the database
# and create random heat for each symbol
for (sym, co, idex) in s_and_p_500:
    new_symbol = Symbol(symbol = sym, name = co, index_id = idex, default = True)
    db.session.add(new_symbol)
    db.session.commit()

    #Create the random heat for this symbol
    for day in seed_dates:
        new_heat = RedditHeat(symbol_id = new_symbol.id, date = day, heat = randint(0,8))
        db.session.add(new_heat)
        db.session.commit()